import { ThemeConfig } from '../types/presentation';

export const THEMES: ThemeConfig[] = [
  // DARK TECH / SAAS
  {
    id: 'midnight-tech',
    name: 'Midnight Indigo',
    category: 'Dark Mode',
    bgHex: '#0b0f19',
    cardBgHex: '#161e31',
    cardBorderHex: '#2a3650',
    textHex: '#cbd5e1',
    titleHex: '#ffffff',
    accentHex: '#6366f1',
    mutedHex: '#64748b',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
    cardGlass: true,
  },
  {
    id: 'saas-indigo',
    name: 'SaaS Blue',
    category: 'Dark Mode',
    bgHex: '#090d16',
    cardBgHex: '#121828',
    cardBorderHex: '#1f293d',
    textHex: '#e2e8f0',
    titleHex: '#f8fafc',
    accentHex: '#3b82f6',
    mutedHex: '#94a3b8',
    fontHead: 'grotesk',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'md',
  },
  {
    id: 'deep-space',
    name: 'Deep Obsidian',
    category: 'Dark Mode',
    bgHex: '#030712',
    cardBgHex: '#111827',
    cardBorderHex: '#1f2937',
    textHex: '#d1d5db',
    titleHex: '#f9fafb',
    accentHex: '#8b5cf6',
    mutedHex: '#6b7280',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'titanium-dark',
    name: 'Titanium Stealth',
    category: 'Dark Mode',
    bgHex: '#0d0d0d',
    cardBgHex: '#18181b',
    cardBorderHex: '#27272a',
    textHex: '#a1a1aa',
    titleHex: '#ffffff',
    accentHex: '#e4e4e7',
    mutedHex: '#71717a',
    fontHead: 'grotesk',
    fontBody: 'mono',
    isDark: true,
    borderRadius: 'sm',
  },

  // LIGHT & MINIMAL
  {
    id: 'nordic-light',
    name: 'Nordic Snow',
    category: 'Light Mode',
    bgHex: '#f8fafc',
    cardBgHex: '#ffffff',
    cardBorderHex: '#e2e8f0',
    textHex: '#334155',
    titleHex: '#0f172a',
    accentHex: '#2563eb',
    mutedHex: '#64748b',
    fontHead: 'grotesk',
    fontBody: 'sans',
    isDark: false,
    borderRadius: 'lg',
  },
  {
    id: 'clean-slate',
    name: 'Minimal Canvas',
    category: 'Minimal',
    bgHex: '#ffffff',
    cardBgHex: '#f8fafc',
    cardBorderHex: '#f1f5f9',
    textHex: '#475569',
    titleHex: '#020617',
    accentHex: '#0284c7',
    mutedHex: '#94a3b8',
    fontHead: 'sans',
    fontBody: 'sans',
    isDark: false,
    borderRadius: 'md',
  },
  {
    id: 'editorial-serif',
    name: 'Executive Editorial',
    category: 'Warm & Organic',
    bgHex: '#fcfbf7',
    cardBgHex: '#f4f1ea',
    cardBorderHex: '#e5e0d3',
    textHex: '#27272a',
    titleHex: '#18181b',
    accentHex: '#9f1239',
    mutedHex: '#71717a',
    fontHead: 'editorial',
    fontBody: 'editorial',
    isDark: false,
    borderRadius: 'sm',
  },
  {
    id: 'warm-sand',
    name: 'Warm Desert Sand',
    category: 'Warm & Organic',
    bgHex: '#fdfbf7',
    cardBgHex: '#f5f0e6',
    cardBorderHex: '#e6ded0',
    textHex: '#44403c',
    titleHex: '#1c1917',
    accentHex: '#d97706',
    mutedHex: '#78716c',
    fontHead: 'editorial',
    fontBody: 'sans',
    isDark: false,
    borderRadius: 'lg',
  },

  // VIBRANT & GRADIENT
  {
    id: 'vibrant-sunset',
    name: 'Sunset Rose',
    category: 'Vibrant',
    bgHex: '#110c1d',
    cardBgHex: '#1e1633',
    cardBorderHex: '#332654',
    textHex: '#e2e8f0',
    titleHex: '#ffffff',
    accentHex: '#f43f5e',
    mutedHex: '#a855f7',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'electric-violet',
    name: 'Electric Synth',
    category: 'Vibrant',
    bgHex: '#0f051d',
    cardBgHex: '#1c0c36',
    cardBorderHex: '#33195f',
    textHex: '#e0e7ff',
    titleHex: '#ffffff',
    accentHex: '#a855f7',
    mutedHex: '#818cf8',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'full',
  },
  {
    id: 'coral-flare',
    name: 'Coral Flare',
    category: 'Vibrant',
    bgHex: '#1a090d',
    cardBgHex: '#2b1017',
    cardBorderHex: '#4a1b29',
    textHex: '#fecdd3',
    titleHex: '#fff1f2',
    accentHex: '#fb7185',
    mutedHex: '#fda4af',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
  },

  // CYBER & NEON
  {
    id: 'cyber-dark',
    name: 'Cyber Cyan',
    category: 'Cyber',
    bgHex: '#050505',
    cardBgHex: '#111111',
    cardBorderHex: '#222222',
    textHex: '#d4d4d8',
    titleHex: '#ffffff',
    accentHex: '#06b6d4',
    mutedHex: '#71717a',
    fontHead: 'grotesk',
    fontBody: 'mono',
    isDark: true,
    borderRadius: 'none',
  },
  {
    id: 'matrix-green',
    name: 'Matrix Neon',
    category: 'Cyber',
    bgHex: '#020d08',
    cardBgHex: '#081c12',
    cardBorderHex: '#103824',
    textHex: '#a7f3d0',
    titleHex: '#ecfdf5',
    accentHex: '#10b981',
    mutedHex: '#34d399',
    fontHead: 'grotesk',
    fontBody: 'mono',
    isDark: true,
    borderRadius: 'sm',
  },

  // PASTEL & MODERN
  {
    id: 'pastel-lavender',
    name: 'Soft Lavender',
    category: 'Pastel & Modern',
    bgHex: '#f5f3ff',
    cardBgHex: '#ffffff',
    cardBorderHex: '#ddd6fe',
    textHex: '#4c1d95',
    titleHex: '#2e1065',
    accentHex: '#7c3aed',
    mutedHex: '#8b5cf6',
    fontHead: 'outfit',
    fontBody: 'sans',
    isDark: false,
    borderRadius: 'full',
  },
  {
    id: 'mint-fresh',
    name: 'Fresh Mint Light',
    category: 'Pastel & Modern',
    bgHex: '#f0fdf4',
    cardBgHex: '#ffffff',
    cardBorderHex: '#bbf7d0',
    textHex: '#14532d',
    titleHex: '#052e16',
    accentHex: '#16a34a',
    mutedHex: '#22c55e',
    fontHead: 'montserrat',
    fontBody: 'sans',
    isDark: false,
    borderRadius: 'lg',
  },
  {
    id: 'rose-quartz',
    name: 'Rose Gold Luxury',
    category: 'Pastel & Modern',
    bgHex: '#fff1f2',
    cardBgHex: '#ffffff',
    cardBorderHex: '#fecdd3',
    textHex: '#881337',
    titleHex: '#4c0519',
    accentHex: '#e11d48',
    mutedHex: '#f43f5e',
    fontHead: 'playfair',
    fontBody: 'editorial',
    isDark: false,
    borderRadius: 'lg',
  },
  {
    id: 'nordic-teal',
    name: 'Deep Teal Marine',
    category: 'Corporate',
    bgHex: '#041c1e',
    cardBgHex: '#0a2d30',
    cardBorderHex: '#164e52',
    textHex: '#99f6e4',
    titleHex: '#f0fdfa',
    accentHex: '#14b8a6',
    mutedHex: '#2dd4bf',
    fontHead: 'outfit',
    fontBody: 'inter',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'velvet-plum',
    name: 'Royal Velvet Plum',
    category: 'Vibrant',
    bgHex: '#18041a',
    cardBgHex: '#29082d',
    cardBorderHex: '#47124f',
    textHex: '#f5d0fe',
    titleHex: '#fdf4ff',
    accentHex: '#d946ef',
    mutedHex: '#e879f9',
    fontHead: 'playfair',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'forest-emerald',
    name: 'Forest Emerald',
    category: 'Corporate',
    bgHex: '#06130d',
    cardBgHex: '#0d2218',
    cardBorderHex: '#1a3e2e',
    textHex: '#d1fae5',
    titleHex: '#ecfdf5',
    accentHex: '#10b981',
    mutedHex: '#6ee7b7',
    fontHead: 'display',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'md',
  },
  {
    id: 'royal-navy',
    name: 'Royal Navy Blue',
    category: 'Corporate',
    bgHex: '#0a192f',
    cardBgHex: '#112240',
    cardBorderHex: '#233554',
    textHex: '#8892b0',
    titleHex: '#ccd6f6',
    accentHex: '#64ffda',
    mutedHex: '#8892b0',
    fontHead: 'grotesk',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'md',
  },
  {
    id: 'luxury-gold',
    name: 'Obsidian Gold',
    category: 'Corporate',
    bgHex: '#0c0a09',
    cardBgHex: '#1c1917',
    cardBorderHex: '#292524',
    textHex: '#d6d3d1',
    titleHex: '#fafaf9',
    accentHex: '#eab308',
    mutedHex: '#78716c',
    fontHead: 'editorial',
    fontBody: 'editorial',
    isDark: true,
    borderRadius: 'sm',
  },
  {
    id: 'coffee-roast',
    name: 'Roast Coffee',
    category: 'Warm & Organic',
    bgHex: '#120d0a',
    cardBgHex: '#211712',
    cardBorderHex: '#38281f',
    textHex: '#e7d5c9',
    titleHex: '#fcf8f5',
    accentHex: '#f97316',
    mutedHex: '#a88c7d',
    fontHead: 'editorial',
    fontBody: 'sans',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'desert-terracotta',
    name: 'Desert Terracotta',
    category: 'Warm & Organic',
    bgHex: '#140d0a',
    cardBgHex: '#231610',
    cardBorderHex: '#3c2419',
    textHex: '#fed7aa',
    titleHex: '#ffedd5',
    accentHex: '#ea580c',
    mutedHex: '#fb923c',
    fontHead: 'garamond',
    fontBody: 'inter',
    isDark: true,
    borderRadius: 'lg',
  },
  {
    id: 'sunset-coral',
    name: 'Sunset Coral',
    category: 'Vibrant',
    bgHex: '#120a10',
    cardBgHex: '#22111d',
    cardBorderHex: '#3d1b33',
    textHex: '#fbcfe8',
    titleHex: '#fff1f2',
    accentHex: '#f43f5e',
    mutedHex: '#fb7185',
    fontHead: 'outfit',
    fontBody: 'inter',
    isDark: true,
    borderRadius: 'full',
  },
  {
    id: 'cyber-neon',
    name: 'Cyberpunk Neon',
    category: 'Cyber',
    bgHex: '#050508',
    cardBgHex: '#0c0c16',
    cardBorderHex: '#201b3e',
    textHex: '#a5f3fc',
    titleHex: '#ffffff',
    accentHex: '#06b6d4',
    mutedHex: '#38bdf8',
    fontHead: 'grotesk',
    fontBody: 'jetbrains',
    isDark: true,
    borderRadius: 'sm',
  },
  {
    id: 'emerald-luxe',
    name: 'Emerald Luxe',
    category: 'Corporate',
    bgHex: '#03140e',
    cardBgHex: '#072419',
    cardBorderHex: '#0f3f2d',
    textHex: '#a7f3d0',
    titleHex: '#f0fdf4',
    accentHex: '#10b981',
    mutedHex: '#34d399',
    fontHead: 'playfair',
    fontBody: 'inter',
    isDark: true,
    borderRadius: 'md',
  },
];

export const DEFAULT_THEME = THEMES[0];

export interface FontOption {
  id: string;
  name: string;
  category: 'Modern Sans' | 'Editorial Serif' | 'Geometric' | 'Monospace';
  className: string;
  previewText: string;
}

export const HEADING_FONTS: FontOption[] = [
  { id: 'outfit', name: 'Outfit', category: 'Modern Sans', className: 'font-outfit', previewText: 'Clean & Ultra Modern' },
  { id: 'display', name: 'Syne', category: 'Geometric', className: 'font-display', previewText: 'Bold Avant-Garde' },
  { id: 'grotesk', name: 'Space Grotesk', category: 'Geometric', className: 'font-grotesk', previewText: 'Futuristic Tech' },
  { id: 'playfair', name: 'Playfair Display', category: 'Editorial Serif', className: 'font-playfair', previewText: 'Luxury & Editorial' },
  { id: 'garamond', name: 'Cormorant Garamond', category: 'Editorial Serif', className: 'font-garamond', previewText: 'Timeless Elegance' },
  { id: 'editorial', name: 'Lora', category: 'Editorial Serif', className: 'font-editorial', previewText: 'Literary & Warm' },
  { id: 'montserrat', name: 'Montserrat', category: 'Modern Sans', className: 'font-montserrat', previewText: 'Punchy & Strong' },
  { id: 'inter', name: 'Inter', category: 'Modern Sans', className: 'font-inter', previewText: 'Minimal & Neutral' },
  { id: 'sans', name: 'Plus Jakarta Sans', category: 'Modern Sans', className: 'font-jakarta', previewText: 'Crisp SaaS Standard' },
];

export const BODY_FONTS: FontOption[] = [
  { id: 'inter', name: 'Inter', category: 'Modern Sans', className: 'font-inter', previewText: 'Highest readability' },
  { id: 'sans', name: 'Plus Jakarta', category: 'Modern Sans', className: 'font-jakarta', previewText: 'Modern product copy' },
  { id: 'outfit', name: 'Outfit', category: 'Modern Sans', className: 'font-outfit', previewText: 'Clean modern body' },
  { id: 'editorial', name: 'Lora Serif', category: 'Editorial Serif', className: 'font-editorial', previewText: 'Editorial longform' },
  { id: 'garamond', name: 'Garamond', category: 'Editorial Serif', className: 'font-garamond', previewText: 'Classical aesthetic' },
  { id: 'mono', name: 'Fira Code', category: 'Monospace', className: 'font-code', previewText: 'Technical & Data' },
  { id: 'jetbrains', name: 'JetBrains Mono', category: 'Monospace', className: 'font-jetbrains', previewText: 'Code & Metrics' },
];

export const ACCENT_COLOR_PALETTES = [
  { name: 'Indigo Pulse', hex: '#6366f1' },
  { name: 'Electric Cyan', hex: '#06b6d4' },
  { name: 'Emerald Spark', hex: '#10b981' },
  { name: 'Neon Purple', hex: '#a855f7' },
  { name: 'Sunset Rose', hex: '#f43f5e' },
  { name: 'Amber Gold', hex: '#f59e0b' },
  { name: 'Royal Blue', hex: '#3b82f6' },
  { name: 'Coral Flare', hex: '#ff6b4a' },
  { name: 'Pastel Lilac', hex: '#c084fc' },
  { name: 'Mint Teal', hex: '#14b8a6' },
];

export const CANVAS_BG_PALETTES = [
  { name: 'Midnight Dark', hex: '#0b0f19' },
  { name: 'Obsidian Black', hex: '#030712' },
  { name: 'Deep Space', hex: '#090d16' },
  { name: 'Titanium Slate', hex: '#0d0d0d' },
  { name: 'Royal Navy', hex: '#0a192f' },
  { name: 'Velvet Wine', hex: '#18041a' },
  { name: 'Forest Night', hex: '#03140e' },
  { name: 'Nordic Snow', hex: '#f8fafc' },
  { name: 'Pure White', hex: '#ffffff' },
  { name: 'Warm Cream', hex: '#fbf9f5' },
];
